# Generated by Django 5.1.2 on 2024-11-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_yearcls',
            new_name='publication_year',
        ),
    ]
